general:
  s3_regional_buckets: true

project:
  name: aws-utility-meter-data-analytics-platform-v2
  owner: rodekamp@amazon.de
  lambda_source_path: source/lambda
  lambda_zip_path: assets/lambda
  regions:
    - us-east-1
    - us-east-2
    - us-west-2
    - eu-west-1

tests:
  full-test-all-regions:
    parameters:
      MeterDataGenerator: 'ENABLED'
      TotalDevices: 0
      GrafanaDashboard: 'ENABLED'
      GrafanaDashboardAuthenticationProvider: 'SAML'
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: aws-utility-meter-data-analytics-platform-v2/
      QSS3BucketRegion: $[taskcat_current_region]
    template: ./templates/work-load.template.yaml
