AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates glue S3 buckets and upload scripts to it. (qs-1r18anahd)"
Resources:
  IntegrationEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: "MDAIntegrationEventBus"

Outputs:
  IntegrationEventBus:
      Value: !Ref IntegrationEventBus
    
Parameters:
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    Default: aws-quickstart
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    Default: quickstart-aws-utility-meter-data-analytics-platform/
    Type: String
