AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: "Workload template to deploy the AWS Quick Start for the Utility Meter Data Analytics platform in an existing VPC. (qs-1r18anahd)"
Conditions:
  UsingDefaultBucket: !Equals [ !Ref QSS3BucketName, 'aws-quickstart' ]
  DeployMeterGeneratorAndHesSimulator: !Equals [ !Ref MeterDataGenerator, 'ENABLED' ]

Resources:
  CopyGlueScriptsStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/util/copy.scripts.yaml'
        - S3Region:
            !If [ UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion ]
          S3Bucket:
            !If [
              UsingDefaultBucket,
              !Sub '${QSS3BucketName}-${AWS::Region}',
              !Ref QSS3BucketName,
            ]
      Parameters:
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix

  MeterDataGeneratorStack:
    Type: 'AWS::CloudFormation::Stack'
    Condition: DeployMeterGeneratorAndHesSimulator
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-aws-utility-meter-data-generator/templates/workload.template.yaml'
        - S3Region:
            !If [ UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion ]
          S3Bucket:
            !If [
              UsingDefaultBucket,
              !Sub '${QSS3BucketName}-${AWS::Region}',
              !Ref QSS3BucketName,
            ]
      Parameters:
        GenerationState: 'ENABLED'
        GenerationInterval: !Ref GenerationInterval
        TotalDevices: !Ref TotalDevices
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Sub '${QSS3KeyPrefix}submodules/quickstart-aws-utility-meter-data-generator/'
        QSS3BucketRegion: !Ref QSS3BucketRegion

  IntegrationStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/integration/integration.yaml'
        - S3Region:
            !If [ UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion ]
          S3Bucket:
            !If [
              UsingDefaultBucket,
              !Sub '${QSS3BucketName}-${AWS::Region}',
              !Ref QSS3BucketName,
            ]

  DataStorageStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/datastorage/datastorage.template.yaml'
        - S3Region:
            !If [ UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion ]
          S3Bucket:
            !If [
              UsingDefaultBucket,
              !Sub '${QSS3BucketName}-${AWS::Region}',
              !Ref QSS3BucketName,
            ]

  MeterreadingsDataflowStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/dataflow/meterreading/meterreading.dataflow.template.yaml'
        - S3Region:
            !If [ UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion ]
          S3Bucket:
            !If [
              UsingDefaultBucket,
              !Sub '${QSS3BucketName}-${AWS::Region}',
              !Ref QSS3BucketName,
            ]
      Parameters:
        StagingDataBucket: !GetAtt DataStorageStack.Outputs.StagingDataBucket
        IntegratedDataBucket: !GetAtt DataStorageStack.Outputs.IntegratedDataBucket
        GlueStagingDatabase: !GetAtt DataStorageStack.Outputs.GlueStagingDatabase
        GlueIntegratedDatabase: !GetAtt DataStorageStack.Outputs.GlueIntegratedDatabase
        MdaGlueScriptBucket: !GetAtt CopyGlueScriptsStack.Outputs.MdaGlueScriptBucket
        IntegrationBus: !GetAtt IntegrationStack.Outputs.IntegrationEventBus
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        QSS3BucketRegion: !Ref QSS3BucketRegion

  HesAdapterStack:
    Type: 'AWS::CloudFormation::Stack'
    Condition: DeployMeterGeneratorAndHesSimulator
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/integration/hes.adapter.yaml'
        - S3Region:
            !If [ UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion ]
          S3Bucket:
            !If [
              UsingDefaultBucket,
              !Sub '${QSS3BucketName}-${AWS::Region}',
              !Ref QSS3BucketName,
            ]
      Parameters:
        OrchestratorState: "ENABLED"
        OrchestratorInterval: !Ref GenerationInterval
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        SFTPServerAddress: !GetAtt MeterDataGeneratorStack.Outputs.SftpServerAddress
        SFTPUserName: !GetAtt MeterDataGeneratorStack.Outputs.SftpUserName
        SFTPSecretARN: !GetAtt MeterDataGeneratorStack.Outputs.SecretARN
        ReadingsFileBaseURL: !GetAtt MeterDataGeneratorStack.Outputs.apiGatewayInvokeURL
        InboundDataBucket: !GetAtt MeterreadingsDataflowStack.Outputs.InboundDataBucket

  WeatherDataflowStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/dataflow/weather/weather.dataflow.template.yaml'
        - S3Region:
            !If [ UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion ]
          S3Bucket:
            !If [
              UsingDefaultBucket,
              !Sub '${QSS3BucketName}-${AWS::Region}',
              !Ref QSS3BucketName,
            ]
      Parameters:
        StagingDataBucket: !GetAtt DataStorageStack.Outputs.StagingDataBucket
        IntegratedDataBucket: !GetAtt DataStorageStack.Outputs.IntegratedDataBucket
        GlueStagingDatabase: !GetAtt DataStorageStack.Outputs.GlueStagingDatabase
        GlueIntegratedDatabase: !GetAtt DataStorageStack.Outputs.GlueIntegratedDatabase
        MdaGlueScriptBucket: !GetAtt CopyGlueScriptsStack.Outputs.MdaGlueScriptBucket
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        QSS3BucketRegion: !Ref QSS3BucketRegion

  TopologyDataflowStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/dataflow/topology/topology.dataflow.template.yaml'
        - S3Region:
            !If [ UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion ]
          S3Bucket:
            !If [
              UsingDefaultBucket,
              !Sub '${QSS3BucketName}-${AWS::Region}',
              !Ref QSS3BucketName,
            ]
      Parameters:
        StagingDataBucket: !GetAtt DataStorageStack.Outputs.StagingDataBucket
        IntegratedDataBucket: !GetAtt DataStorageStack.Outputs.IntegratedDataBucket
        GlueStagingDatabase: !GetAtt DataStorageStack.Outputs.GlueStagingDatabase
        GlueIntegratedDatabase: !GetAtt DataStorageStack.Outputs.GlueIntegratedDatabase
        MdaGlueScriptBucket: !GetAtt CopyGlueScriptsStack.Outputs.MdaGlueScriptBucket
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        QSS3BucketRegion: !Ref QSS3BucketRegion

  VoltVarFeatureStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/feature/voltvar/voltvar.feature.template.yaml'
        - S3Region:
            !If [ UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion ]
          S3Bucket:
            !If [
              UsingDefaultBucket,
              !Sub '${QSS3BucketName}-${AWS::Region}',
              !Ref QSS3BucketName,
            ]
      Parameters:
        IntegratedDataBucket: !GetAtt DataStorageStack.Outputs.IntegratedDataBucket
        GlueIntegratedDatabase: !GetAtt DataStorageStack.Outputs.GlueIntegratedDatabase
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        QSS3BucketRegion: !Ref QSS3BucketRegion

Outputs:
  StackName:
    Description: 'Stack name'
    Value: !Sub '${AWS::StackName}'
  StagingDataBucket:
    Description: S3 Bucket that contains the staging data.
    Value: !GetAtt DataStorageStack.Outputs.StagingDataBucket
  IntegratedDataBucket:
    Description: S3 Bucket that contains the integrated data.
    Value: !GetAtt DataStorageStack.Outputs.IntegratedDataBucket

Parameters:
  MeterDataGenerator:
    Default: 'DISABLED'
    AllowedValues:
      - 'ENABLED'
      - 'DISABLED'
    Description:
      Enable or disable the meter simulator. If disabled the simulation stack will NOT be deployed.
      If enabled the meter generator as well as HES simulator will be deployed, and both start to generate meter reads immediately.
      (additional costs can occur).
    Type: String
  GenerationInterval:
    Description: 'Minutes per interval, must be greater than 5.'
    Type: Number
    Default: 5
    MinValue: 5
    ConstraintDescription: 'GenerationInterval must contain a numeric value greater than 5.'
  TotalDevices:
    Description: 'Number of devices to generate readings at each interval.'
    Type: Number
    Default: 50000
  QSS3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription:
      The Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a
      hyphen (-).
    Default: aws-quickstart
    Description:
      Name of the S3 bucket for your copy of the Quick Start assets.
      Keep the default name unless you are customizing the template.
      Changing the name updates code references to point to a new Quick
      Start location. This name can include numbers, lowercase letters,
      uppercase letters, and hyphens, but do not start or end with a hyphen (-).
      See https://aws-quickstart.github.io/option1.html.
    Type: String
  
  QSS3KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/]*$'
    ConstraintDescription:
      The Quick Start S3 key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slashes (/). The prefix should
      end with a forward slash (/).
    Default: quickstart-aws-utility-meter-data-analytics-platform/
    Description:
      S3 key prefix that is used to simulate a directory for your copy of the
      Quick Start assets. Keep the default prefix unless you are customizing
      the template. Changing this prefix updates code references to point to
      a new Quick Start location. This prefix can include numbers, lowercase
      letters, uppercase letters, hyphens (-), and forward slashes (/). End with
      a forward slash. See https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html
      and https://aws-quickstart.github.io/option1.html.
    Type: String
  
  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: 'AWS Region where the Quick Start S3 bucket (QSS3BucketName) is 
    hosted. Keep the default Region unless you are customizing the template. 
    Changing this Region updates code references to point to a new Quick Start location. 
    When using your own bucket, specify the Region. 
    See https://aws-quickstart.github.io/option1.html.'
    Type: String


Metadata:
  QuickStartDocumentation:
    EntrypointName: "Parameters for deploying into an existing VPC"
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Meter data generator configuration'
        Parameters:
          - MeterDataGenerator
          - GenerationInterval
          - TotalDevices
      - Label:
          default: 'AWS Quick Start configuration'
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix
          - QSS3BucketRegion
    ParameterLabels:
      MeterDataGenerator:
        default: Enable/disable the generator
      GenerationInterval:
        default: Interval in which new meter reads will be generated
      TotalDevices:
        default: Number of devices
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
      QSS3BucketRegion:
        default: Quick Start S3 bucket Region
